/* Generated by cfg-gen for tests/integration/integration.schema */
#ifndef GENERATED_INTEGRATION_H
#define GENERATED_INTEGRATION_H

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef enum {
    CFG_SUCCESS = 0,
    CFG_ERR_OPEN_FILE,
    CFG_ERR_SYNTAX,
    CFG_ERR_VALIDATION,
} cfg_status_t;

typedef struct {
    char message[512];
    char field[256];
    size_t line;
} cfg_error_t;

#include "integration_hooks.h"

typedef struct {
    uint8_t octets[4];
} cfg_ipv4_t;

typedef struct NestedConfig_t NestedConfig_t;
typedef struct TestSuite_t TestSuite_t;
typedef struct EdgeCaseTest_t EdgeCaseTest_t;

typedef struct NestedConfig_t {
    int64_t nested_id;
    bool active;
    void* internal_pool;
} NestedConfig_t;

typedef enum {
    TestSuite_global_level_DEBUG,
    TestSuite_global_level_INFO,
    TestSuite_global_level_WARN,
    TestSuite_global_level_ERROR,
} TestSuite_global_level_t;

typedef struct level4_t {
    int64_t depth;
    struct { const char* *data; size_t count; } tags;
} level4_t;

typedef struct level3_t {
    bool debug_mode;
    const char* log_file;
    level4_t level4;
} level3_t;

typedef struct level2_t {
    cfg_ipv4_t bind_addr;
    level3_t level3;
} level2_t;

typedef struct level1_t {
    double factor;
    level2_t level2;
} level1_t;

typedef struct TestSuite_t {
    const char* project_name;
    int64_t version;
    const char* api_key;
    level1_t level1;
    TestSuite_global_level_t global_level;
    void* internal_pool;
} TestSuite_t;

typedef struct weird_t {
    const char* key_with_dash;
} weird_t;

typedef struct EdgeCaseTest_t {
    const char* empty_str;
    const char* space_str;
    bool flag_true;
    bool flag_1;
    bool flag_false;
    bool flag_0;
    const char* hook_field;
    struct { int64_t *data; size_t count; } int_array;
    NestedConfig_t sub;
    weird_t weird;
    void* internal_pool;
} EdgeCaseTest_t;

cfg_status_t NestedConfig_load(NestedConfig_t *cfg, const char *filename, int argc, const char **argv, cfg_error_t *err);
void NestedConfig_parse_cli(NestedConfig_t *cfg, int argc, const char **argv);
void NestedConfig_print(const NestedConfig_t *cfg, FILE *f);
void NestedConfig_free(NestedConfig_t *cfg);
bool NestedConfig_validate(const NestedConfig_t *cfg, cfg_error_t *err);
cfg_status_t TestSuite_load(TestSuite_t *cfg, const char *filename, int argc, const char **argv, cfg_error_t *err);
void TestSuite_parse_cli(TestSuite_t *cfg, int argc, const char **argv);
void TestSuite_print(const TestSuite_t *cfg, FILE *f);
void TestSuite_free(TestSuite_t *cfg);
bool TestSuite_validate(const TestSuite_t *cfg, cfg_error_t *err);
bool level1_validate(const level1_t *cfg, cfg_error_t *err);
bool level2_validate(const level2_t *cfg, cfg_error_t *err);
bool level3_validate(const level3_t *cfg, cfg_error_t *err);
bool level4_validate(const level4_t *cfg, cfg_error_t *err);
cfg_status_t EdgeCaseTest_load(EdgeCaseTest_t *cfg, const char *filename, int argc, const char **argv, cfg_error_t *err);
void EdgeCaseTest_parse_cli(EdgeCaseTest_t *cfg, int argc, const char **argv);
void EdgeCaseTest_print(const EdgeCaseTest_t *cfg, FILE *f);
void EdgeCaseTest_free(EdgeCaseTest_t *cfg);
bool EdgeCaseTest_validate(const EdgeCaseTest_t *cfg, cfg_error_t *err);
bool weird_validate(const weird_t *cfg, cfg_error_t *err);

#endif /* GENERATED_INTEGRATION_H */

#ifdef CONFIG_IMPLEMENTATION

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#ifndef CFG_FILE_EXISTS
#ifdef _WIN32
#include <io.h>
#define CFG_FILE_EXISTS(path) (_access((path), 0) == 0)
#else
#include <unistd.h>
#define CFG_FILE_EXISTS(path) (access((path), F_OK) == 0)
#endif
#endif /* CFG_FILE_EXISTS */
typedef struct cfg_pool_node {
    void *ptr;
    struct cfg_pool_node *next;
} cfg_pool_node_t;

static void* cfg_pool_alloc(cfg_pool_node_t **head, size_t size) {
    void *ptr = malloc(size);
    if (!ptr) return NULL;
    cfg_pool_node_t *node = (cfg_pool_node_t*)malloc(sizeof(cfg_pool_node_t));
    if (!node) { free(ptr); return NULL; }
    node->ptr = ptr;
    node->next = *head;
    *head = node;
    return ptr;
}

static void cfg_pool_free(cfg_pool_node_t *head) {
    while (head) {
        cfg_pool_node_t *next = head->next;
        free(head->ptr);
        free(head);
        head = next;
    }
}

typedef struct {
    void *cfg;
    cfg_pool_node_t *pool;
} cfg_common_context_t;

static const char* cfg_intern_string(cfg_common_context_t *ctx, const char *s) {
    if (!s) return NULL;
    char *copy = (char*)cfg_pool_alloc(&ctx->pool, strlen(s) + 1);
    if (copy) strcpy(copy, s);
    return copy;
}

static void cfg_parse_array(cfg_common_context_t *ctx, const char *val, void **data, size_t *count) {
    char *val_copy = (char*)malloc(strlen(val) + 1);
    if (!val_copy) return;
    strcpy(val_copy, val);
    char *s = val_copy;
    char *token = strtok(s, ",");
    size_t n = 0;
    while (token) { n++; token = strtok(NULL, ","); }
    free(val_copy);
    *count = n;
    if (n == 0) { *data = NULL; return; }
    *data = cfg_pool_alloc(&ctx->pool, n * sizeof(const char*));
    val_copy = (char*)malloc(strlen(val) + 1);
    if (!val_copy) return;
    strcpy(val_copy, val);
    s = val_copy;
    token = strtok(s, ",");
    for (size_t i = 0; i < n; i++) {
        while(isspace(*token)) token++;
        char *end = token + strlen(token) - 1;
        while(end > token && isspace(*end)) *end-- = '\0';
        ((const char**)*data)[i] = cfg_intern_string(ctx, token);
        token = strtok(NULL, ",");
    }
    free(val_copy);
}

static bool cfg_parse_ipv4(const char *s, cfg_ipv4_t *out) {
    int octets[4];
    if (sscanf(s, "%d.%d.%d.%d", &octets[0], &octets[1], &octets[2], &octets[3]) != 4) return false;
    for (int i = 0; i < 4; i++) { if (octets[i] < 0 || octets[i] > 255) return false; out->octets[i] = (uint8_t)octets[i]; }
    return true;
}

static void cfg_set_error(cfg_error_t *err, const char *msg, const char *field, size_t line) {
    if (!err) return;
    if (msg) { strncpy(err->message, msg, sizeof(err->message) - 1); err->message[sizeof(err->message) - 1] = '\0'; }
    if (field) { strncpy(err->field, field, sizeof(err->field) - 1); err->field[sizeof(err->field) - 1] = '\0'; }
    err->line = line;
}

typedef void (*cfg_ini_cb)(void *user, const char *sec, const char *key, const char *val);
static cfg_status_t cfg_parse_ini(const char *filename, cfg_ini_cb cb, void *user, cfg_error_t *err) {
    FILE *f = fopen(filename, "r"); if (!f) { cfg_set_error(err, "failed to open file", filename, 0); return CFG_ERR_OPEN_FILE; }
    char line[4096], section[256] = "";
    size_t line_num = 0; bool success = true;
    while (fgets(line, sizeof(line), f)) {
        line_num++; char *p = line; while(isspace(*p)) p++;
        if (*p == '\0' || *p == ';' || *p == '#') continue;
        if (*p == '[') {
            char *end = strchr(p, ']');
            if (end) {
                size_t len = end - (p + 1);
                if (len >= sizeof(section)) len = sizeof(section) - 1;
                strncpy(section, p + 1, len);
                section[len] = '\0';
            } else { cfg_set_error(err, "missing closing bracket for section", section, line_num); success = false; }
        } else {
            char *eq = strchr(p, '=');
            if (eq) {
                *eq = '\0'; char *key = p, *val = eq + 1;
                char *k_end = key + strlen(key) - 1; while(k_end > key && isspace(*k_end)) *k_end-- = '\0';
                while(isspace(*val)) val++;
                char *v_end = val + strlen(val) - 1; while(v_end > val && isspace(*v_end)) *v_end-- = '\0';
                cb(user, section, key, val);
            } else {
                cfg_set_error(err, "missing assignment operator", p, line_num); success = false;
            }
        }
    }
    fclose(f);
    return success ? CFG_SUCCESS : CFG_ERR_SYNTAX;
}

static bool cfg_pattern_0_match(const char *s) {
    if (!s) return false;
    const char *start = s;
        const char *p = start;
    { char c = *p; if (c == '\0' || !((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_' || c == '-')) return false; }
    p++;
    while (*p != '\0') { char c = *p; if (!((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_' || c == '-')) break; p++; }
    if (*p == '\0') return true;
    return false;
}

bool NestedConfig_validate(const NestedConfig_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (!test_nested_hook(&cfg->nested_id, err)) return false;
    return true;
}

void NestedConfig_print(const NestedConfig_t *cfg, FILE *f) {
    if (!cfg) return;
    if (!f) f = stdout;
    fprintf(f, "--- NestedConfig Configuration ---\n");
    fprintf(f, "%*snested_id = ", 0, "");
    fprintf(f, "%lld\n", (long long)cfg->nested_id);
    fprintf(f, "%*sactive = ", 0, "");
    fprintf(f, "%s\n", cfg->active ? "true" : "false");
    fprintf(f, "--------------------------\n");
}

static void NestedConfig_ini_handler_recursive(cfg_common_context_t *ctx, const char *key, const char *val, char **parts, int num_parts, int depth) {
    if (num_parts == 0) {
        if (strcmp(key, "nested_id") == 0) {
            ((NestedConfig_t*)ctx->cfg)->nested_id = strtoll(val, NULL, 10);
            return;
        }
        if (strcmp(key, "active") == 0) {
            ((NestedConfig_t*)ctx->cfg)->active = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
            return;
        }
    }
}

static bool NestedConfig_parse_arg(cfg_common_context_t *ctx, int argc, const char **argv, int *index) {
    int i = *index;
    const char *arg = argv[i];
    if (strcmp(arg, "--NestedConfig.nested_id") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((NestedConfig_t*)ctx->cfg)->nested_id = strtoll(val, NULL, 10);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--NestedConfig.nested_id=", 25) == 0) {
        const char *val = arg + 25;
        ((NestedConfig_t*)ctx->cfg)->nested_id = strtoll(val, NULL, 10);
        return true;
    }
    if (strcmp(arg, "--NestedConfig.active") == 0 || (arg[0] == '-' && arg[1] == 'a' && arg[2] == '\0')) {
        ((NestedConfig_t*)ctx->cfg)->active = true; return true;
    }
    *index = i;
    return false;
}

void NestedConfig_parse_cli(NestedConfig_t *cfg, int argc, const char **argv) {
    if (!cfg || !argv || argc <= 1) return;
    cfg_common_context_t ctx = { cfg, (cfg_pool_node_t*)cfg->internal_pool };
    for (int i = 1; i < argc; i++) {
        if (argv[i][0] != '-') continue;
        NestedConfig_parse_arg(&ctx, argc, argv, &i);
    }
    cfg->internal_pool = ctx.pool;
}

static void NestedConfig_ini_handler(void *user, const char *sec, const char *key, const char *val) {
    cfg_common_context_t *ctx = (cfg_common_context_t*)user;
    char sec_copy[256];
    strncpy(sec_copy, sec, sizeof(sec_copy) - 1);
    sec_copy[sizeof(sec_copy) - 1] = '\0';
    char *parts[32]; int num_parts = 0;
    char *token = strtok(sec_copy, ".");
    while(token && num_parts < 32) { parts[num_parts++] = token; token = strtok(NULL, "."); }

    if (num_parts == 0 || strcmp(parts[0], "NestedConfig") != 0) return;
    for (int i = 0; i < num_parts - 1; i++) parts[i] = parts[i+1];
    num_parts--;

    NestedConfig_ini_handler_recursive(ctx, key, val, parts, num_parts, 0);
}

cfg_status_t NestedConfig_load(NestedConfig_t *cfg, const char *filename, int argc, const char **argv, cfg_error_t *err) {
    if (!cfg) return CFG_ERR_VALIDATION;
    memset(cfg, 0, sizeof(NestedConfig_t));
    cfg_common_context_t ctx = { cfg, NULL };
    if (err) memset(err, 0, sizeof(cfg_error_t));
    cfg->nested_id = 99;
    cfg->active = true;
    if (filename) {
        cfg_status_t status = cfg_parse_ini(filename, NestedConfig_ini_handler, &ctx, err);
        if (status != CFG_SUCCESS) { cfg_pool_free(ctx.pool); return status; }
    }
    cfg->internal_pool = ctx.pool;
    NestedConfig_parse_cli(cfg, argc, argv);
    if (!NestedConfig_validate(cfg, err)) { NestedConfig_free(cfg); return CFG_ERR_VALIDATION; }
    return CFG_SUCCESS;
}

void NestedConfig_free(NestedConfig_t *cfg) {
    if (!cfg) return;
    cfg_pool_free((cfg_pool_node_t*)cfg->internal_pool);
    memset(cfg, 0, sizeof(NestedConfig_t));
}

bool TestSuite_validate(const TestSuite_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (cfg->project_name == NULL) { cfg_set_error(err, "required field missing", "project_name", 0); return false; }
    if (cfg->project_name != NULL && strlen(cfg->project_name) < 3) { cfg_set_error(err, "string too short", "project_name", 0); return false; }
    if (cfg->project_name != NULL && !cfg_pattern_0_match(cfg->project_name)) { cfg_set_error(err, "pattern mismatch", "project_name", 0); return false; }
    if (cfg->version < 1 || cfg->version > 100) { cfg_set_error(err, "value out of range", "version", 0); return false; }
    if (!level1_validate(&cfg->level1, err)) return false;
    return true;
}

bool level1_validate(const level1_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (cfg->factor < 0.000000) { cfg_set_error(err, "value too small", "factor", 0); return false; }
    if (cfg->factor > 1.000000) { cfg_set_error(err, "value too large", "factor", 0); return false; }
    if (!level2_validate(&cfg->level2, err)) return false;
    return true;
}

bool level2_validate(const level2_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (!level3_validate(&cfg->level3, err)) return false;
    return true;
}

bool level3_validate(const level3_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (cfg->log_file != NULL && !CFG_FILE_EXISTS(cfg->log_file)) { cfg_set_error(err, "file does not exist", "log_file", 0); return false; }
    if (cfg->debug_mode == true) {
        if (cfg->log_file == NULL) { cfg_set_error(err, "field required by condition missing", "log_file", 0); return false; }
    }
    if (!level4_validate(&cfg->level4, err)) return false;
    return true;
}

bool level4_validate(const level4_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (cfg->tags.count < 1) { cfg_set_error(err, "array too short", "tags", 0); return false; }
    if (!test_array_hook(&cfg->tags, err)) return false;
    return true;
}

void TestSuite_print(const TestSuite_t *cfg, FILE *f) {
    if (!cfg) return;
    if (!f) f = stdout;
    fprintf(f, "--- TestSuite Configuration ---\n");
    fprintf(f, "%*sproject_name = ", 0, "");
    fprintf(f, "\"%s\"\n", cfg->project_name ? cfg->project_name : "null");
    fprintf(f, "%*sversion = ", 0, "");
    fprintf(f, "%lld\n", (long long)cfg->version);
    fprintf(f, "%*sapi_key = ", 0, "");
    fprintf(f, "********\n");
    fprintf(f, "%*s[level1]\n", 0, "");
    fprintf(f, "%*sfactor = ", 2, "");
    fprintf(f, "%f\n", cfg->level1.factor);
    fprintf(f, "%*s[level2]\n", 2, "");
    fprintf(f, "%*sbind_addr = ", 4, "");
    fprintf(f, "%u.%u.%u.%u\n", cfg->level1.level2.bind_addr.octets[0], cfg->level1.level2.bind_addr.octets[1], cfg->level1.level2.bind_addr.octets[2], cfg->level1.level2.bind_addr.octets[3]);
    fprintf(f, "%*s[level3]\n", 4, "");
    fprintf(f, "%*sdebug_mode = ", 6, "");
    fprintf(f, "%s\n", cfg->level1.level2.level3.debug_mode ? "true" : "false");
    fprintf(f, "%*slog_file = ", 6, "");
    fprintf(f, "\"%s\"\n", cfg->level1.level2.level3.log_file ? cfg->level1.level2.level3.log_file : "null");
    fprintf(f, "%*s[level4]\n", 6, "");
    fprintf(f, "%*sdepth = ", 8, "");
    fprintf(f, "%lld\n", (long long)cfg->level1.level2.level3.level4.depth);
    fprintf(f, "%*stags = ", 8, "");
    fprintf(f, "[ ");
    for (size_t i = 0; i < cfg->level1.level2.level3.level4.tags.count; i++) fprintf(f, "%s%s", i > 0 ? ", " : "", ((const char**)cfg->level1.level2.level3.level4.tags.data)[i]);
    fprintf(f, " ]\n");
    fprintf(f, "%*sglobal_level = ", 0, "");
    fprintf(f, "%d (enum)\n", (int)cfg->global_level);
    fprintf(f, "--------------------------\n");
}

static void TestSuite_ini_handler_recursive(cfg_common_context_t *ctx, const char *key, const char *val, char **parts, int num_parts, int depth) {
    if (num_parts == 0) {
        if (strcmp(key, "project_name") == 0) {
            ((TestSuite_t*)ctx->cfg)->project_name = cfg_intern_string(ctx, val);
            return;
        }
        if (strcmp(key, "version") == 0) {
            ((TestSuite_t*)ctx->cfg)->version = strtoll(val, NULL, 10);
            return;
        }
        if (strcmp(key, "api_key") == 0) {
            ((TestSuite_t*)ctx->cfg)->api_key = cfg_intern_string(ctx, val);
            return;
        }
        if (strcmp(key, "global_level") == 0) {
            if (strcmp(val, "DEBUG") == 0) ((TestSuite_t*)ctx->cfg)->global_level = TestSuite_global_level_DEBUG;
            else if (strcmp(val, "INFO") == 0) ((TestSuite_t*)ctx->cfg)->global_level = TestSuite_global_level_INFO;
            else if (strcmp(val, "WARN") == 0) ((TestSuite_t*)ctx->cfg)->global_level = TestSuite_global_level_WARN;
            else if (strcmp(val, "ERROR") == 0) ((TestSuite_t*)ctx->cfg)->global_level = TestSuite_global_level_ERROR;
            return;
        }
    }
    if (0 < num_parts && strcmp(parts[0], "level1") == 0) {
        if (num_parts == 1) {
            if (strcmp(key, "factor") == 0) {
                ((TestSuite_t*)ctx->cfg)->level1.factor = strtod(val, NULL);
                return;
            }
        }
        if (1 < num_parts && strcmp(parts[1], "level2") == 0) {
            if (num_parts == 2) {
                if (strcmp(key, "bind_addr") == 0) {
                    cfg_parse_ipv4(val, &((TestSuite_t*)ctx->cfg)->level1.level2.bind_addr);
                    return;
                }
            }
            if (2 < num_parts && strcmp(parts[2], "level3") == 0) {
                if (num_parts == 3) {
                    if (strcmp(key, "debug_mode") == 0) {
                        ((TestSuite_t*)ctx->cfg)->level1.level2.level3.debug_mode = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
                        return;
                    }
                    if (strcmp(key, "log_file") == 0) {
                        ((TestSuite_t*)ctx->cfg)->level1.level2.level3.log_file = cfg_intern_string(ctx, val);
                        return;
                    }
                }
                if (3 < num_parts && strcmp(parts[3], "level4") == 0) {
                    if (num_parts == 4) {
                        if (strcmp(key, "depth") == 0) {
                            ((TestSuite_t*)ctx->cfg)->level1.level2.level3.level4.depth = strtoll(val, NULL, 10);
                            return;
                        }
                        if (strcmp(key, "tags") == 0) {
                            cfg_parse_array(ctx, val, (void**)&((TestSuite_t*)ctx->cfg)->level1.level2.level3.level4.tags.data, &((TestSuite_t*)ctx->cfg)->level1.level2.level3.level4.tags.count);
                            return;
                        }
                    }
                }
            }
        }
    }
}

static bool TestSuite_parse_arg(cfg_common_context_t *ctx, int argc, const char **argv, int *index) {
    int i = *index;
    const char *arg = argv[i];
    if (strcmp(arg, "--TestSuite.project_name") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((TestSuite_t*)ctx->cfg)->project_name = cfg_intern_string(ctx, val);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--TestSuite.project_name=", 25) == 0) {
        const char *val = arg + 25;
        ((TestSuite_t*)ctx->cfg)->project_name = cfg_intern_string(ctx, val);
        return true;
    }
    if (strcmp(arg, "--TestSuite.version") == 0 || (arg[0] == '-' && arg[1] == 'v' && arg[2] == '\0')) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((TestSuite_t*)ctx->cfg)->version = strtoll(val, NULL, 10);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--TestSuite.version=", 20) == 0) {
        const char *val = arg + 20;
        ((TestSuite_t*)ctx->cfg)->version = strtoll(val, NULL, 10);
        return true;
    }
    if (strcmp(arg, "--TestSuite.api_key") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((TestSuite_t*)ctx->cfg)->api_key = cfg_intern_string(ctx, val);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--TestSuite.api_key=", 20) == 0) {
        const char *val = arg + 20;
        ((TestSuite_t*)ctx->cfg)->api_key = cfg_intern_string(ctx, val);
        return true;
    }
    if (strcmp(arg, "--TestSuite.level1.factor") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((TestSuite_t*)ctx->cfg)->level1.factor = strtod(val, NULL);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--TestSuite.level1.factor=", 26) == 0) {
        const char *val = arg + 26;
        ((TestSuite_t*)ctx->cfg)->level1.factor = strtod(val, NULL);
        return true;
    }
    if (strcmp(arg, "--TestSuite.level1.level2.bind_addr") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            cfg_parse_ipv4(val, &((TestSuite_t*)ctx->cfg)->level1.level2.bind_addr);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--TestSuite.level1.level2.bind_addr=", 36) == 0) {
        const char *val = arg + 36;
        cfg_parse_ipv4(val, &((TestSuite_t*)ctx->cfg)->level1.level2.bind_addr);
        return true;
    }
    if (strcmp(arg, "--TestSuite.level1.level2.level3.debug_mode") == 0) {
        ((TestSuite_t*)ctx->cfg)->level1.level2.level3.debug_mode = true; return true;
    }
    if (strcmp(arg, "--TestSuite.level1.level2.level3.log_file") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((TestSuite_t*)ctx->cfg)->level1.level2.level3.log_file = cfg_intern_string(ctx, val);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--TestSuite.level1.level2.level3.log_file=", 42) == 0) {
        const char *val = arg + 42;
        ((TestSuite_t*)ctx->cfg)->level1.level2.level3.log_file = cfg_intern_string(ctx, val);
        return true;
    }
    if (strcmp(arg, "--TestSuite.level1.level2.level3.level4.depth") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((TestSuite_t*)ctx->cfg)->level1.level2.level3.level4.depth = strtoll(val, NULL, 10);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--TestSuite.level1.level2.level3.level4.depth=", 46) == 0) {
        const char *val = arg + 46;
        ((TestSuite_t*)ctx->cfg)->level1.level2.level3.level4.depth = strtoll(val, NULL, 10);
        return true;
    }
    if (strcmp(arg, "--TestSuite.level1.level2.level3.level4.tags") == 0) {
        if (i + 1 < argc) {
            cfg_parse_array(ctx, argv[++i], (void**)&((TestSuite_t*)ctx->cfg)->level1.level2.level3.level4.tags.data, &((TestSuite_t*)ctx->cfg)->level1.level2.level3.level4.tags.count);
            *index = i; return true;
        }
    }
    if (strcmp(arg, "--TestSuite.global_level") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            if (strcmp(val, "DEBUG") == 0) ((TestSuite_t*)ctx->cfg)->global_level = TestSuite_global_level_DEBUG;
            else if (strcmp(val, "INFO") == 0) ((TestSuite_t*)ctx->cfg)->global_level = TestSuite_global_level_INFO;
            else if (strcmp(val, "WARN") == 0) ((TestSuite_t*)ctx->cfg)->global_level = TestSuite_global_level_WARN;
            else if (strcmp(val, "ERROR") == 0) ((TestSuite_t*)ctx->cfg)->global_level = TestSuite_global_level_ERROR;
            *index = i; return true;
        }
    }
    *index = i;
    return false;
}

void TestSuite_parse_cli(TestSuite_t *cfg, int argc, const char **argv) {
    if (!cfg || !argv || argc <= 1) return;
    cfg_common_context_t ctx = { cfg, (cfg_pool_node_t*)cfg->internal_pool };
    for (int i = 1; i < argc; i++) {
        if (argv[i][0] != '-') continue;
        TestSuite_parse_arg(&ctx, argc, argv, &i);
    }
    cfg->internal_pool = ctx.pool;
}

static void TestSuite_ini_handler(void *user, const char *sec, const char *key, const char *val) {
    cfg_common_context_t *ctx = (cfg_common_context_t*)user;
    char sec_copy[256];
    strncpy(sec_copy, sec, sizeof(sec_copy) - 1);
    sec_copy[sizeof(sec_copy) - 1] = '\0';
    char *parts[32]; int num_parts = 0;
    char *token = strtok(sec_copy, ".");
    while(token && num_parts < 32) { parts[num_parts++] = token; token = strtok(NULL, "."); }

    if (num_parts == 0 || strcmp(parts[0], "TestSuite") != 0) return;
    for (int i = 0; i < num_parts - 1; i++) parts[i] = parts[i+1];
    num_parts--;

    TestSuite_ini_handler_recursive(ctx, key, val, parts, num_parts, 0);
}

cfg_status_t TestSuite_load(TestSuite_t *cfg, const char *filename, int argc, const char **argv, cfg_error_t *err) {
    if (!cfg) return CFG_ERR_VALIDATION;
    memset(cfg, 0, sizeof(TestSuite_t));
    cfg_common_context_t ctx = { cfg, NULL };
    if (err) memset(err, 0, sizeof(cfg_error_t));
    cfg->version = 1;
    cfg->api_key = cfg_intern_string(&ctx, "super-secret-key");
    cfg->level1.factor = 0.500000;
    cfg_parse_ipv4("127.0.0.1", &cfg->level1.level2.bind_addr);
    cfg->level1.level2.level3.debug_mode = false;
    cfg->level1.level2.level3.level4.depth = 4;
    cfg->global_level = TestSuite_global_level_INFO;
    if (filename) {
        cfg_status_t status = cfg_parse_ini(filename, TestSuite_ini_handler, &ctx, err);
        if (status != CFG_SUCCESS) { cfg_pool_free(ctx.pool); return status; }
    }
    { const char *e = getenv("BIND_ADDR"); if (e) { cfg_parse_ipv4(e, &cfg->level1.level2.bind_addr); } }
    cfg->internal_pool = ctx.pool;
    TestSuite_parse_cli(cfg, argc, argv);
    if (!TestSuite_validate(cfg, err)) { TestSuite_free(cfg); return CFG_ERR_VALIDATION; }
    return CFG_SUCCESS;
}

void TestSuite_free(TestSuite_t *cfg) {
    if (!cfg) return;
    cfg_pool_free((cfg_pool_node_t*)cfg->internal_pool);
    memset(cfg, 0, sizeof(TestSuite_t));
}

bool EdgeCaseTest_validate(const EdgeCaseTest_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (!test_hook(cfg->hook_field, err)) return false;
    if (cfg->int_array.count < 2) { cfg_set_error(err, "array too short", "int_array", 0); return false; }
    if (!NestedConfig_validate(&cfg->sub, err)) return false;
    if (!weird_validate(&cfg->weird, err)) return false;
    return true;
}

bool weird_validate(const weird_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    return true;
}

void EdgeCaseTest_print(const EdgeCaseTest_t *cfg, FILE *f) {
    if (!cfg) return;
    if (!f) f = stdout;
    fprintf(f, "--- EdgeCaseTest Configuration ---\n");
    fprintf(f, "%*sempty_str = ", 0, "");
    fprintf(f, "\"%s\"\n", cfg->empty_str ? cfg->empty_str : "null");
    fprintf(f, "%*sspace_str = ", 0, "");
    fprintf(f, "\"%s\"\n", cfg->space_str ? cfg->space_str : "null");
    fprintf(f, "%*sflag_true = ", 0, "");
    fprintf(f, "%s\n", cfg->flag_true ? "true" : "false");
    fprintf(f, "%*sflag_1 = ", 0, "");
    fprintf(f, "%s\n", cfg->flag_1 ? "true" : "false");
    fprintf(f, "%*sflag_false = ", 0, "");
    fprintf(f, "%s\n", cfg->flag_false ? "true" : "false");
    fprintf(f, "%*sflag_0 = ", 0, "");
    fprintf(f, "%s\n", cfg->flag_0 ? "true" : "false");
    fprintf(f, "%*shook_field = ", 0, "");
    fprintf(f, "\"%s\"\n", cfg->hook_field ? cfg->hook_field : "null");
    fprintf(f, "%*sint_array = ", 0, "");
    fprintf(f, "[ ");
    for (size_t i = 0; i < cfg->int_array.count; i++) fprintf(f, "%s%s", i > 0 ? ", " : "", ((const char**)cfg->int_array.data)[i]);
    fprintf(f, " ]\n");
    fprintf(f, "%*ssub = ", 0, "");
    fprintf(f, "{\n");
    fprintf(f, "%*snested_id = ", 2, "");
    fprintf(f, "%lld\n", (long long)cfg->sub.nested_id);
    fprintf(f, "%*sactive = ", 2, "");
    fprintf(f, "%s\n", cfg->sub.active ? "true" : "false");
    fprintf(f, "%*s}\n", 0, "");
    fprintf(f, "%*s[weird]\n", 0, "");
    fprintf(f, "%*skey_with_dash = ", 2, "");
    fprintf(f, "\"%s\"\n", cfg->weird.key_with_dash ? cfg->weird.key_with_dash : "null");
    fprintf(f, "--------------------------\n");
}

static void EdgeCaseTest_ini_handler_recursive(cfg_common_context_t *ctx, const char *key, const char *val, char **parts, int num_parts, int depth) {
    if (num_parts == 0) {
        if (strcmp(key, "empty_str") == 0) {
            ((EdgeCaseTest_t*)ctx->cfg)->empty_str = cfg_intern_string(ctx, val);
            return;
        }
        if (strcmp(key, "space_str") == 0) {
            ((EdgeCaseTest_t*)ctx->cfg)->space_str = cfg_intern_string(ctx, val);
            return;
        }
        if (strcmp(key, "flag_true") == 0) {
            ((EdgeCaseTest_t*)ctx->cfg)->flag_true = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
            return;
        }
        if (strcmp(key, "flag_1") == 0) {
            ((EdgeCaseTest_t*)ctx->cfg)->flag_1 = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
            return;
        }
        if (strcmp(key, "flag_false") == 0) {
            ((EdgeCaseTest_t*)ctx->cfg)->flag_false = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
            return;
        }
        if (strcmp(key, "flag_0") == 0) {
            ((EdgeCaseTest_t*)ctx->cfg)->flag_0 = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
            return;
        }
        if (strcmp(key, "hook_field") == 0) {
            ((EdgeCaseTest_t*)ctx->cfg)->hook_field = cfg_intern_string(ctx, val);
            return;
        }
        if (strcmp(key, "int_array") == 0) {
            cfg_parse_array(ctx, val, (void**)&((EdgeCaseTest_t*)ctx->cfg)->int_array.data, &((EdgeCaseTest_t*)ctx->cfg)->int_array.count);
            return;
        }
        if (strcmp(key, "sub") == 0) {
            return;
        }
    }
    if (0 < num_parts && strcmp(parts[0], "sub") == 0) {
        if (num_parts == 1) {
            if (strcmp(key, "nested_id") == 0) {
                ((EdgeCaseTest_t*)ctx->cfg)->sub.nested_id = strtoll(val, NULL, 10);
                return;
            }
            if (strcmp(key, "active") == 0) {
                ((EdgeCaseTest_t*)ctx->cfg)->sub.active = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
                return;
            }
        }
    }
    if (0 < num_parts && strcmp(parts[0], "weird") == 0) {
        if (num_parts == 1) {
            if (strcmp(key, "key_with_dash") == 0) {
                ((EdgeCaseTest_t*)ctx->cfg)->weird.key_with_dash = cfg_intern_string(ctx, val);
                return;
            }
        }
    }
}

static bool EdgeCaseTest_parse_arg(cfg_common_context_t *ctx, int argc, const char **argv, int *index) {
    int i = *index;
    const char *arg = argv[i];
    if (strcmp(arg, "--EdgeCaseTest.empty_str") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((EdgeCaseTest_t*)ctx->cfg)->empty_str = cfg_intern_string(ctx, val);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--EdgeCaseTest.empty_str=", 25) == 0) {
        const char *val = arg + 25;
        ((EdgeCaseTest_t*)ctx->cfg)->empty_str = cfg_intern_string(ctx, val);
        return true;
    }
    if (strcmp(arg, "--EdgeCaseTest.space_str") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((EdgeCaseTest_t*)ctx->cfg)->space_str = cfg_intern_string(ctx, val);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--EdgeCaseTest.space_str=", 25) == 0) {
        const char *val = arg + 25;
        ((EdgeCaseTest_t*)ctx->cfg)->space_str = cfg_intern_string(ctx, val);
        return true;
    }
    if (strcmp(arg, "--EdgeCaseTest.flag_true") == 0) {
        ((EdgeCaseTest_t*)ctx->cfg)->flag_true = true; return true;
    }
    if (strcmp(arg, "--EdgeCaseTest.flag_1") == 0) {
        ((EdgeCaseTest_t*)ctx->cfg)->flag_1 = true; return true;
    }
    if (strcmp(arg, "--EdgeCaseTest.flag_false") == 0) {
        ((EdgeCaseTest_t*)ctx->cfg)->flag_false = true; return true;
    }
    if (strcmp(arg, "--EdgeCaseTest.flag_0") == 0) {
        ((EdgeCaseTest_t*)ctx->cfg)->flag_0 = true; return true;
    }
    if (strcmp(arg, "--EdgeCaseTest.hook_field") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((EdgeCaseTest_t*)ctx->cfg)->hook_field = cfg_intern_string(ctx, val);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--EdgeCaseTest.hook_field=", 26) == 0) {
        const char *val = arg + 26;
        ((EdgeCaseTest_t*)ctx->cfg)->hook_field = cfg_intern_string(ctx, val);
        return true;
    }
    if (strcmp(arg, "--EdgeCaseTest.int_array") == 0) {
        if (i + 1 < argc) {
            cfg_parse_array(ctx, argv[++i], (void**)&((EdgeCaseTest_t*)ctx->cfg)->int_array.data, &((EdgeCaseTest_t*)ctx->cfg)->int_array.count);
            *index = i; return true;
        }
    }
    if (strcmp(arg, "--EdgeCaseTest.sub.nested_id") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((EdgeCaseTest_t*)ctx->cfg)->sub.nested_id = strtoll(val, NULL, 10);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--EdgeCaseTest.sub.nested_id=", 29) == 0) {
        const char *val = arg + 29;
        ((EdgeCaseTest_t*)ctx->cfg)->sub.nested_id = strtoll(val, NULL, 10);
        return true;
    }
    if (strcmp(arg, "--EdgeCaseTest.sub.active") == 0 || (arg[0] == '-' && arg[1] == 'a' && arg[2] == '\0')) {
        ((EdgeCaseTest_t*)ctx->cfg)->sub.active = true; return true;
    }
    if (strcmp(arg, "--EdgeCaseTest.weird.key_with_dash") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((EdgeCaseTest_t*)ctx->cfg)->weird.key_with_dash = cfg_intern_string(ctx, val);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--EdgeCaseTest.weird.key_with_dash=", 35) == 0) {
        const char *val = arg + 35;
        ((EdgeCaseTest_t*)ctx->cfg)->weird.key_with_dash = cfg_intern_string(ctx, val);
        return true;
    }
    *index = i;
    return false;
}

void EdgeCaseTest_parse_cli(EdgeCaseTest_t *cfg, int argc, const char **argv) {
    if (!cfg || !argv || argc <= 1) return;
    cfg_common_context_t ctx = { cfg, (cfg_pool_node_t*)cfg->internal_pool };
    for (int i = 1; i < argc; i++) {
        if (argv[i][0] != '-') continue;
        EdgeCaseTest_parse_arg(&ctx, argc, argv, &i);
    }
    cfg->internal_pool = ctx.pool;
}

static void EdgeCaseTest_ini_handler(void *user, const char *sec, const char *key, const char *val) {
    cfg_common_context_t *ctx = (cfg_common_context_t*)user;
    char sec_copy[256];
    strncpy(sec_copy, sec, sizeof(sec_copy) - 1);
    sec_copy[sizeof(sec_copy) - 1] = '\0';
    char *parts[32]; int num_parts = 0;
    char *token = strtok(sec_copy, ".");
    while(token && num_parts < 32) { parts[num_parts++] = token; token = strtok(NULL, "."); }

    if (num_parts == 0 || strcmp(parts[0], "EdgeCaseTest") != 0) return;
    for (int i = 0; i < num_parts - 1; i++) parts[i] = parts[i+1];
    num_parts--;

    EdgeCaseTest_ini_handler_recursive(ctx, key, val, parts, num_parts, 0);
}

cfg_status_t EdgeCaseTest_load(EdgeCaseTest_t *cfg, const char *filename, int argc, const char **argv, cfg_error_t *err) {
    if (!cfg) return CFG_ERR_VALIDATION;
    memset(cfg, 0, sizeof(EdgeCaseTest_t));
    cfg_common_context_t ctx = { cfg, NULL };
    if (err) memset(err, 0, sizeof(cfg_error_t));
    cfg->empty_str = cfg_intern_string(&ctx, "unknown");
    cfg->space_str = cfg_intern_string(&ctx, " ");
    cfg->flag_true = false;
    cfg->flag_1 = false;
    cfg->flag_false = true;
    cfg->flag_0 = true;
    cfg->hook_field = cfg_intern_string(&ctx, "hook-ok");
    cfg->sub.nested_id = 99;
    cfg->sub.active = true;
    cfg->weird.key_with_dash = cfg_intern_string(&ctx, "dash");
    if (filename) {
        cfg_status_t status = cfg_parse_ini(filename, EdgeCaseTest_ini_handler, &ctx, err);
        if (status != CFG_SUCCESS) { cfg_pool_free(ctx.pool); return status; }
    }
    cfg->internal_pool = ctx.pool;
    EdgeCaseTest_parse_cli(cfg, argc, argv);
    if (!EdgeCaseTest_validate(cfg, err)) { EdgeCaseTest_free(cfg); return CFG_ERR_VALIDATION; }
    return CFG_SUCCESS;
}

void EdgeCaseTest_free(EdgeCaseTest_t *cfg) {
    if (!cfg) return;
    cfg_pool_free((cfg_pool_node_t*)cfg->internal_pool);
    memset(cfg, 0, sizeof(EdgeCaseTest_t));
}

#endif /* CONFIG_IMPLEMENTATION */
