/* Generated by cfg-gen for ../examples/config.schema */
#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct {
    uint8_t octets[4];
} cfg_ipv4_t;

typedef enum {
    CFG_SUCCESS = 0,
    CFG_ERR_OPEN_FILE,
    CFG_ERR_SYNTAX,
    CFG_ERR_VALIDATION,
} cfg_status_t;

typedef struct {
    char message[512];
    char field[256];
    size_t line;
} cfg_error_t;

typedef struct DatabaseConfig_t DatabaseConfig_t;
typedef struct AuthConfig_t AuthConfig_t;
typedef struct ApiGateway_t ApiGateway_t;

typedef enum {
    DatabaseConfig_driver_postgres,
    DatabaseConfig_driver_mysql,
    DatabaseConfig_driver_sqlite,
} DatabaseConfig_driver_t;

typedef struct DatabaseConfig_t {
    DatabaseConfig_driver_t driver;
    const char* host;
    int64_t port;
    int64_t pool_size;
    void* internal_pool;
} DatabaseConfig_t;

typedef enum {
    AuthConfig_provider_jwt,
    AuthConfig_provider_oauth2,
    AuthConfig_provider_basic,
} AuthConfig_provider_t;

typedef struct AuthConfig_t {
    bool enabled;
    AuthConfig_provider_t provider;
    int64_t token_ttl;
    void* internal_pool;
} AuthConfig_t;

typedef enum {
    logging_level_debug,
    logging_level_info,
    logging_level_warn,
    logging_level_error,
} logging_level_t;

typedef struct logging_t {
    logging_level_t level;
    const char* file_path;
    int64_t max_backups;
} logging_t;

typedef struct caching_t {
    bool enabled;
    struct { const char* *data; size_t count; } nodes;
    int64_t ttl;
} caching_t;

typedef struct ApiGateway_t {
    const char* service_name;
    cfg_ipv4_t bind_address;
    int64_t listen_port;
    bool enable_tls;
    const char* cert_path;
    DatabaseConfig_t database;
    AuthConfig_t auth;
    logging_t logging;
    caching_t caching;
    void* internal_pool;
} ApiGateway_t;

cfg_status_t DatabaseConfig_load(DatabaseConfig_t *cfg, const char *filename, cfg_error_t *err);
void DatabaseConfig_free(DatabaseConfig_t *cfg);
bool DatabaseConfig_validate(const DatabaseConfig_t *cfg, cfg_error_t *err);
cfg_status_t AuthConfig_load(AuthConfig_t *cfg, const char *filename, cfg_error_t *err);
void AuthConfig_free(AuthConfig_t *cfg);
bool AuthConfig_validate(const AuthConfig_t *cfg, cfg_error_t *err);
cfg_status_t ApiGateway_load(ApiGateway_t *cfg, const char *filename, cfg_error_t *err);
void ApiGateway_free(ApiGateway_t *cfg);
bool ApiGateway_validate(const ApiGateway_t *cfg, cfg_error_t *err);
bool logging_validate(const logging_t *cfg, cfg_error_t *err);
bool caching_validate(const caching_t *cfg, cfg_error_t *err);

#endif /* CONFIG_H */

#ifdef CONFIG_IMPLEMENTATION

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#ifndef CFG_FILE_EXISTS
#ifdef _WIN32
#include <io.h>
#define CFG_FILE_EXISTS(path) (_access((path), 0) == 0)
#else
#include <unistd.h>
#define CFG_FILE_EXISTS(path) (access((path), F_OK) == 0)
#endif
#endif /* CFG_FILE_EXISTS */

typedef struct cfg_pool_node {
    void *ptr;
    struct cfg_pool_node *next;
} cfg_pool_node_t;

static void* cfg_pool_alloc(cfg_pool_node_t **head, size_t size) {
    void *ptr = malloc(size);
    if (!ptr) return NULL;
    cfg_pool_node_t *node = (cfg_pool_node_t*)malloc(sizeof(cfg_pool_node_t));
    if (!node) { free(ptr); return NULL; }
    node->ptr = ptr;
    node->next = *head;
    *head = node;
    return ptr;
}

static void cfg_pool_free(cfg_pool_node_t *head) {
    while (head) {
        cfg_pool_node_t *next = head->next;
        free(head->ptr);
        free(head);
        head = next;
    }
}

typedef struct {
    void *cfg;
    cfg_pool_node_t *pool;
} cfg_common_context_t;

static const char* cfg_intern_string(cfg_common_context_t *ctx, const char *s) {
    if (!s) return NULL;
    char *copy = (char*)cfg_pool_alloc(&ctx->pool, strlen(s) + 1);
    if (copy) strcpy(copy, s);
    return copy;
}

static void cfg_parse_array(cfg_common_context_t *ctx, const char *val, void **data, size_t *count) {
    char *val_copy = (char*)malloc(strlen(val) + 1);
    if (!val_copy) return;
    strcpy(val_copy, val);
    char *s = val_copy;
    char *token = strtok(s, ",");
    size_t n = 0;
    while (token) { n++; token = strtok(NULL, ","); }
    free(val_copy);
    *count = n;
    if (n == 0) { *data = NULL; return; }
    *data = cfg_pool_alloc(&ctx->pool, n * sizeof(const char*));
    val_copy = (char*)malloc(strlen(val) + 1);
    if (!val_copy) return;
    strcpy(val_copy, val);
    s = val_copy;
    token = strtok(s, ",");
    for (size_t i = 0; i < n; i++) {
        while(isspace(*token)) token++;
        char *end = token + strlen(token) - 1;
        while(end > token && isspace(*end)) *end-- = '\0';
        ((const char**)*data)[i] = cfg_intern_string(ctx, token);
        token = strtok(NULL, ",");
    }
    free(val_copy);
}

static bool cfg_parse_ipv4(const char *s, cfg_ipv4_t *out) {
    int octets[4];
    if (sscanf(s, "%d.%d.%d.%d", &octets[0], &octets[1], &octets[2], &octets[3]) != 4) return false;
    for (int i = 0; i < 4; i++) { if (octets[i] < 0 || octets[i] > 255) return false; out->octets[i] = (uint8_t)octets[i]; }
    return true;
}

static void cfg_set_error(cfg_error_t *err, const char *msg, const char *field, size_t line) {
    if (!err) return;
    if (msg) { strncpy(err->message, msg, sizeof(err->message) - 1); err->message[sizeof(err->message) - 1] = '\0'; }
    if (field) { strncpy(err->field, field, sizeof(err->field) - 1); err->field[sizeof(err->field) - 1] = '\0'; }
    err->line = line;
}

typedef void (*cfg_ini_cb)(void *user, const char *sec, const char *key, const char *val);
static cfg_status_t cfg_parse_ini(const char *filename, cfg_ini_cb cb, void *user, cfg_error_t *err) {
    FILE *f = fopen(filename, "r"); if (!f) { cfg_set_error(err, "failed to open file", filename, 0); return CFG_ERR_OPEN_FILE; }
    char line[4096], section[256] = "";
    size_t line_num = 0; bool success = true;
    while (fgets(line, sizeof(line), f)) {
        line_num++; char *p = line; while(isspace(*p)) p++;
        if (*p == '\0' || *p == ';' || *p == '#') continue;
        if (*p == '[') {
            char *end = strchr(p, ']');
            if (end) {
                size_t len = end - (p + 1);
                if (len >= sizeof(section)) len = sizeof(section) - 1;
                strncpy(section, p + 1, len);
                section[len] = '\0';
            } else { cfg_set_error(err, "missing closing bracket for section", section, line_num); success = false; }
        } else {
            char *eq = strchr(p, '=');
            if (eq) {
                *eq = '\0'; char *key = p, *val = eq + 1;
                char *k_end = key + strlen(key) - 1; while(k_end > key && isspace(*k_end)) *k_end-- = '\0';
                while(isspace(*val)) val++;
                char *v_end = val + strlen(val) - 1; while(v_end > val && isspace(*v_end)) *v_end-- = '\0';
                cb(user, section, key, val);
            } else {
                cfg_set_error(err, "missing assignment operator", p, line_num); success = false;
            }
        }
    }
    fclose(f);
    return success ? CFG_SUCCESS : CFG_ERR_SYNTAX;
}

static bool cfg_pattern_0_match(const char *s) {
    if (!s) return false;
    const char *start = s;
        const char *p = start;
    { char c = *p; if (c == '\0' || !((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-')) return false; }
    p++;
    while (*p != '\0') { char c = *p; if (!((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-')) break; p++; }
    if (*p == '\0') return true;
    return false;
}

bool DatabaseConfig_validate(const DatabaseConfig_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (cfg->port < 1 || cfg->port > 65535) { cfg_set_error(err, "value out of range", "port", 0); return false; }
    if (cfg->pool_size < 1 || cfg->pool_size > 100) { cfg_set_error(err, "value out of range", "pool_size", 0); return false; }
    return true;
}

static void DatabaseConfig_ini_handler_recursive(cfg_common_context_t *ctx, const char *key, const char *val, char **parts, int num_parts, int depth) {
    if (num_parts == 0) {
        if (strcmp(key, "driver") == 0) {
            if (strcmp(val, "postgres") == 0) ((DatabaseConfig_t*)ctx->cfg)->driver = DatabaseConfig_driver_postgres;
            else if (strcmp(val, "mysql") == 0) ((DatabaseConfig_t*)ctx->cfg)->driver = DatabaseConfig_driver_mysql;
            else if (strcmp(val, "sqlite") == 0) ((DatabaseConfig_t*)ctx->cfg)->driver = DatabaseConfig_driver_sqlite;
            return;
        }
        if (strcmp(key, "host") == 0) {
            ((DatabaseConfig_t*)ctx->cfg)->host = cfg_intern_string(ctx, val);
            return;
        }
        if (strcmp(key, "port") == 0) {
            ((DatabaseConfig_t*)ctx->cfg)->port = strtoll(val, NULL, 10);
            return;
        }
        if (strcmp(key, "pool_size") == 0) {
            ((DatabaseConfig_t*)ctx->cfg)->pool_size = strtoll(val, NULL, 10);
            return;
        }
    }
}

static void DatabaseConfig_ini_handler(void *user, const char *sec, const char *key, const char *val) {
    cfg_common_context_t *ctx = (cfg_common_context_t*)user;
    char sec_copy[256];
    strncpy(sec_copy, sec, sizeof(sec_copy) - 1);
    sec_copy[sizeof(sec_copy) - 1] = '\0';
    char *parts[32]; int num_parts = 0;
    char *token = strtok(sec_copy, ".");
    while(token && num_parts < 32) { parts[num_parts++] = token; token = strtok(NULL, "."); }

    if (num_parts > 0 && strcmp(parts[0], "DatabaseConfig") == 0) {
        for (int i = 0; i < num_parts - 1; i++) parts[i] = parts[i+1];
        num_parts--;
    }

    DatabaseConfig_ini_handler_recursive(ctx, key, val, parts, num_parts, 0);
}

cfg_status_t DatabaseConfig_load(DatabaseConfig_t *cfg, const char *filename, cfg_error_t *err) {
    if (!cfg) return CFG_ERR_VALIDATION;
    memset(cfg, 0, sizeof(DatabaseConfig_t));
    cfg_common_context_t ctx = { cfg, NULL };
    if (err) memset(err, 0, sizeof(cfg_error_t));
    cfg->driver = DatabaseConfig_driver_postgres;
    cfg->host = cfg_intern_string(&ctx, "localhost");
    cfg->port = 5432;
    cfg->pool_size = 10;
    if (filename) {
        cfg_status_t status = cfg_parse_ini(filename, DatabaseConfig_ini_handler, &ctx, err);
        if (status != CFG_SUCCESS) { cfg_pool_free(ctx.pool); return status; }
    }
    { const char *e = getenv("DB_HOST"); if (e) { cfg->host = cfg_intern_string(&ctx, e); } }
    cfg->internal_pool = ctx.pool;
    if (!DatabaseConfig_validate(cfg, err)) { DatabaseConfig_free(cfg); return CFG_ERR_VALIDATION; }
    return CFG_SUCCESS;
}

void DatabaseConfig_free(DatabaseConfig_t *cfg) {
    if (!cfg) return;
    cfg_pool_free((cfg_pool_node_t*)cfg->internal_pool);
    memset(cfg, 0, sizeof(DatabaseConfig_t));
}

bool AuthConfig_validate(const AuthConfig_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (cfg->token_ttl < 60 || cfg->token_ttl > 86400) { cfg_set_error(err, "value out of range", "token_ttl", 0); return false; }
    return true;
}

static void AuthConfig_ini_handler_recursive(cfg_common_context_t *ctx, const char *key, const char *val, char **parts, int num_parts, int depth) {
    if (num_parts == 0) {
        if (strcmp(key, "enabled") == 0) {
            ((AuthConfig_t*)ctx->cfg)->enabled = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
            return;
        }
        if (strcmp(key, "provider") == 0) {
            if (strcmp(val, "jwt") == 0) ((AuthConfig_t*)ctx->cfg)->provider = AuthConfig_provider_jwt;
            else if (strcmp(val, "oauth2") == 0) ((AuthConfig_t*)ctx->cfg)->provider = AuthConfig_provider_oauth2;
            else if (strcmp(val, "basic") == 0) ((AuthConfig_t*)ctx->cfg)->provider = AuthConfig_provider_basic;
            return;
        }
        if (strcmp(key, "token_ttl") == 0) {
            ((AuthConfig_t*)ctx->cfg)->token_ttl = strtoll(val, NULL, 10);
            return;
        }
    }
}

static void AuthConfig_ini_handler(void *user, const char *sec, const char *key, const char *val) {
    cfg_common_context_t *ctx = (cfg_common_context_t*)user;
    char sec_copy[256];
    strncpy(sec_copy, sec, sizeof(sec_copy) - 1);
    sec_copy[sizeof(sec_copy) - 1] = '\0';
    char *parts[32]; int num_parts = 0;
    char *token = strtok(sec_copy, ".");
    while(token && num_parts < 32) { parts[num_parts++] = token; token = strtok(NULL, "."); }

    if (num_parts > 0 && strcmp(parts[0], "AuthConfig") == 0) {
        for (int i = 0; i < num_parts - 1; i++) parts[i] = parts[i+1];
        num_parts--;
    }

    AuthConfig_ini_handler_recursive(ctx, key, val, parts, num_parts, 0);
}

cfg_status_t AuthConfig_load(AuthConfig_t *cfg, const char *filename, cfg_error_t *err) {
    if (!cfg) return CFG_ERR_VALIDATION;
    memset(cfg, 0, sizeof(AuthConfig_t));
    cfg_common_context_t ctx = { cfg, NULL };
    if (err) memset(err, 0, sizeof(cfg_error_t));
    cfg->enabled = true;
    cfg->provider = AuthConfig_provider_jwt;
    cfg->token_ttl = 3600;
    if (filename) {
        cfg_status_t status = cfg_parse_ini(filename, AuthConfig_ini_handler, &ctx, err);
        if (status != CFG_SUCCESS) { cfg_pool_free(ctx.pool); return status; }
    }
    cfg->internal_pool = ctx.pool;
    if (!AuthConfig_validate(cfg, err)) { AuthConfig_free(cfg); return CFG_ERR_VALIDATION; }
    return CFG_SUCCESS;
}

void AuthConfig_free(AuthConfig_t *cfg) {
    if (!cfg) return;
    cfg_pool_free((cfg_pool_node_t*)cfg->internal_pool);
    memset(cfg, 0, sizeof(AuthConfig_t));
}

bool ApiGateway_validate(const ApiGateway_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (cfg->service_name != NULL && strlen(cfg->service_name) < 3) { cfg_set_error(err, "string too short", "service_name", 0); return false; }
    if (cfg->service_name != NULL && !cfg_pattern_0_match(cfg->service_name)) { cfg_set_error(err, "pattern mismatch", "service_name", 0); return false; }
    if (cfg->listen_port < 80 || cfg->listen_port > 9000) { cfg_set_error(err, "value out of range", "listen_port", 0); return false; }
    if (cfg->enable_tls == true) {
        if (cfg->cert_path == NULL) { cfg_set_error(err, "field required by condition missing", "cert_path", 0); return false; }
    }
    if (cfg->cert_path != NULL && !CFG_FILE_EXISTS(cfg->cert_path)) { cfg_set_error(err, "file does not exist", "cert_path", 0); return false; }
    if (!DatabaseConfig_validate(&cfg->database, err)) return false;
    if (!AuthConfig_validate(&cfg->auth, err)) return false;
    if (!logging_validate(&cfg->logging, err)) return false;
    if (!caching_validate(&cfg->caching, err)) return false;
    return true;
}

bool logging_validate(const logging_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (cfg->max_backups < 0 || cfg->max_backups > 100) { cfg_set_error(err, "value out of range", "max_backups", 0); return false; }
    return true;
}

bool caching_validate(const caching_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    if (cfg->nodes.count < 1) { cfg_set_error(err, "array too short", "nodes", 0); return false; }
    if (cfg->enabled == true) {
        if (cfg->nodes.count == 0) { cfg_set_error(err, "field required by condition missing", "nodes", 0); return false; }
    }
    if (cfg->ttl < 0 || cfg->ttl > 3600) { cfg_set_error(err, "value out of range", "ttl", 0); return false; }
    return true;
}

static void ApiGateway_ini_handler_recursive(cfg_common_context_t *ctx, const char *key, const char *val, char **parts, int num_parts, int depth) {
    if (num_parts == 0) {
        if (strcmp(key, "service_name") == 0) {
            ((ApiGateway_t*)ctx->cfg)->service_name = cfg_intern_string(ctx, val);
            return;
        }
        if (strcmp(key, "bind_address") == 0) {
            cfg_parse_ipv4(val, &((ApiGateway_t*)ctx->cfg)->bind_address);
            return;
        }
        if (strcmp(key, "listen_port") == 0) {
            ((ApiGateway_t*)ctx->cfg)->listen_port = strtoll(val, NULL, 10);
            return;
        }
        if (strcmp(key, "enable_tls") == 0) {
            ((ApiGateway_t*)ctx->cfg)->enable_tls = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
            return;
        }
        if (strcmp(key, "cert_path") == 0) {
            ((ApiGateway_t*)ctx->cfg)->cert_path = cfg_intern_string(ctx, val);
            return;
        }
        if (strcmp(key, "database") == 0) {
            return;
        }
        if (strcmp(key, "auth") == 0) {
            return;
        }
    }
    if (0 < num_parts && strcmp(parts[0], "database") == 0) {
        if (num_parts == 1) {
            if (strcmp(key, "driver") == 0) {
                if (strcmp(val, "postgres") == 0) ((ApiGateway_t*)ctx->cfg)->database.driver = DatabaseConfig_driver_postgres;
                else if (strcmp(val, "mysql") == 0) ((ApiGateway_t*)ctx->cfg)->database.driver = DatabaseConfig_driver_mysql;
                else if (strcmp(val, "sqlite") == 0) ((ApiGateway_t*)ctx->cfg)->database.driver = DatabaseConfig_driver_sqlite;
                return;
            }
            if (strcmp(key, "host") == 0) {
                ((ApiGateway_t*)ctx->cfg)->database.host = cfg_intern_string(ctx, val);
                return;
            }
            if (strcmp(key, "port") == 0) {
                ((ApiGateway_t*)ctx->cfg)->database.port = strtoll(val, NULL, 10);
                return;
            }
            if (strcmp(key, "pool_size") == 0) {
                ((ApiGateway_t*)ctx->cfg)->database.pool_size = strtoll(val, NULL, 10);
                return;
            }
        }
    }
    if (0 < num_parts && strcmp(parts[0], "auth") == 0) {
        if (num_parts == 1) {
            if (strcmp(key, "enabled") == 0) {
                ((ApiGateway_t*)ctx->cfg)->auth.enabled = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
                return;
            }
            if (strcmp(key, "provider") == 0) {
                if (strcmp(val, "jwt") == 0) ((ApiGateway_t*)ctx->cfg)->auth.provider = AuthConfig_provider_jwt;
                else if (strcmp(val, "oauth2") == 0) ((ApiGateway_t*)ctx->cfg)->auth.provider = AuthConfig_provider_oauth2;
                else if (strcmp(val, "basic") == 0) ((ApiGateway_t*)ctx->cfg)->auth.provider = AuthConfig_provider_basic;
                return;
            }
            if (strcmp(key, "token_ttl") == 0) {
                ((ApiGateway_t*)ctx->cfg)->auth.token_ttl = strtoll(val, NULL, 10);
                return;
            }
        }
    }
    if (0 < num_parts && strcmp(parts[0], "logging") == 0) {
        if (num_parts == 1) {
            if (strcmp(key, "level") == 0) {
                if (strcmp(val, "debug") == 0) ((ApiGateway_t*)ctx->cfg)->logging.level = logging_level_debug;
                else if (strcmp(val, "info") == 0) ((ApiGateway_t*)ctx->cfg)->logging.level = logging_level_info;
                else if (strcmp(val, "warn") == 0) ((ApiGateway_t*)ctx->cfg)->logging.level = logging_level_warn;
                else if (strcmp(val, "error") == 0) ((ApiGateway_t*)ctx->cfg)->logging.level = logging_level_error;
                return;
            }
            if (strcmp(key, "file_path") == 0) {
                ((ApiGateway_t*)ctx->cfg)->logging.file_path = cfg_intern_string(ctx, val);
                return;
            }
            if (strcmp(key, "max_backups") == 0) {
                ((ApiGateway_t*)ctx->cfg)->logging.max_backups = strtoll(val, NULL, 10);
                return;
            }
        }
    }
    if (0 < num_parts && strcmp(parts[0], "caching") == 0) {
        if (num_parts == 1) {
            if (strcmp(key, "enabled") == 0) {
                ((ApiGateway_t*)ctx->cfg)->caching.enabled = (strcmp(val, "true") == 0 || strcmp(val, "1") == 0);
                return;
            }
            if (strcmp(key, "nodes") == 0) {
                cfg_parse_array(ctx, val, (void**)&((ApiGateway_t*)ctx->cfg)->caching.nodes.data, &((ApiGateway_t*)ctx->cfg)->caching.nodes.count);
                return;
            }
            if (strcmp(key, "ttl") == 0) {
                ((ApiGateway_t*)ctx->cfg)->caching.ttl = strtoll(val, NULL, 10);
                return;
            }
        }
    }
}

static void ApiGateway_ini_handler(void *user, const char *sec, const char *key, const char *val) {
    cfg_common_context_t *ctx = (cfg_common_context_t*)user;
    char sec_copy[256];
    strncpy(sec_copy, sec, sizeof(sec_copy) - 1);
    sec_copy[sizeof(sec_copy) - 1] = '\0';
    char *parts[32]; int num_parts = 0;
    char *token = strtok(sec_copy, ".");
    while(token && num_parts < 32) { parts[num_parts++] = token; token = strtok(NULL, "."); }

    if (num_parts > 0 && strcmp(parts[0], "ApiGateway") == 0) {
        for (int i = 0; i < num_parts - 1; i++) parts[i] = parts[i+1];
        num_parts--;
    }

    ApiGateway_ini_handler_recursive(ctx, key, val, parts, num_parts, 0);
}

cfg_status_t ApiGateway_load(ApiGateway_t *cfg, const char *filename, cfg_error_t *err) {
    if (!cfg) return CFG_ERR_VALIDATION;
    memset(cfg, 0, sizeof(ApiGateway_t));
    cfg_common_context_t ctx = { cfg, NULL };
    if (err) memset(err, 0, sizeof(cfg_error_t));
    cfg->service_name = cfg_intern_string(&ctx, "edge-gateway");
    cfg_parse_ipv4("0.0.0.0", &cfg->bind_address);
    cfg->listen_port = 8080;
    cfg->enable_tls = false;
    cfg->logging.level = logging_level_info;
    cfg->logging.file_path = cfg_intern_string(&ctx, "/var/log/gateway.log");
    cfg->logging.max_backups = 5;
    cfg->caching.enabled = false;
    cfg->caching.ttl = 300;
    if (filename) {
        cfg_status_t status = cfg_parse_ini(filename, ApiGateway_ini_handler, &ctx, err);
        if (status != CFG_SUCCESS) { cfg_pool_free(ctx.pool); return status; }
    }
    { const char *e = getenv("BIND_ADDR"); if (e) { cfg_parse_ipv4(e, &cfg->bind_address); } }
    cfg->internal_pool = ctx.pool;
    if (!ApiGateway_validate(cfg, err)) { ApiGateway_free(cfg); return CFG_ERR_VALIDATION; }
    return CFG_SUCCESS;
}

void ApiGateway_free(ApiGateway_t *cfg) {
    if (!cfg) return;
    cfg_pool_free((cfg_pool_node_t*)cfg->internal_pool);
    memset(cfg, 0, sizeof(ApiGateway_t));
}

#endif /* CONFIG_IMPLEMENTATION */
